-- MySQL Script generated by MySQL Workbench   SUZUMA 2019
-- Mon Sep 25 20:32:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plantilla
-- -----------------------------------------------------
-- Proyecto desarrollado en la materia de……….

-- -----------------------------------------------------
-- Schema plantilla
--
-- Proyecto desarrollado en la materia de……….
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plantilla` DEFAULT CHARACTER SET utf8 ;
USE `plantilla` ;

-- -----------------------------------------------------
-- Table `plantilla`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantilla`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantilla`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantilla`.`estados` (
  `id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantilla`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantilla`.`municipios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `estado_municipio_idx` (`estado_id` ASC),
  CONSTRAINT `estado_municipio`
    FOREIGN KEY (`estado_id`)
    REFERENCES `plantilla`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantilla`.`usuarios`   password default 123456
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantilla`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL DEFAULT '7c4a8d09ca3762af61e59520943dc26494f8941b',
  `rol_id` INT UNSIGNED NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `updated_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `roles_usuario_idx` (`rol_id` ASC),
  CONSTRAINT `roles_usuario`
    FOREIGN KEY (`rol_id`)
    REFERENCES `plantilla`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantilla`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantilla`.`permisos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `update_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plantilla`.`permisos_negados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plantilla`.`permisos_negados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `permiso_id` INT UNSIGNED NOT NULL,
  `rol_id` INT UNSIGNED NOT NULL,
  `crated_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `permiso_negado_idx` (`permiso_id` ASC),
  INDEX `rol_negado_idx` (`rol_id` ASC),
  CONSTRAINT `permiso_negado`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `plantilla`.`permisos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rol_negado`
    FOREIGN KEY (`rol_id`)
    REFERENCES `plantilla`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
